module.exports = {
  'up': `CREATE TABLE Booking (
    Id bigint(20) NOT NULL AUTO_INCREMENT,
    UserId bigint(20) NOT NULL,
    UserDeviceId int(11) DEFAULT NULL,
    ProviderId bigint(20) DEFAULT NULL,
    RideTypeId int(11) DEFAULT NULL,
    FromLocation varchar(255) DEFAULT NULL,
    ToLocation varchar(255) DEFAULT NULL,
    CancelledFor varchar(255) DEFAULT NULL,
    SourceLat decimal(10,6) DEFAULT NULL,
    SourceLong decimal(10,6) DEFAULT NULL,
    DestinyLat decimal(10,6) DEFAULT NULL,
    DestinyLong decimal(10,6) DEFAULT NULL,
    S2CellId varchar(20) DEFAULT NULL,
    Status varchar(45) DEFAULT NULL,
    Distance int(11) DEFAULT NULL,
    Estimation decimal(10,2) DEFAULT NULL,
    CurrencyType longtext CHARACTER SET utf8 COLLATE utf8_general_ci,
    Tax decimal(10,2) DEFAULT '0.00',
    WaitingCharges int(11) DEFAULT NULL,
    TotalAmount decimal(10,2) DEFAULT NULL,
    Description varchar(255) DEFAULT NULL,
    ContactNo varchar(15) DEFAULT NULL,
    CountryId int(11) DEFAULT NULL,
    CancelledBy varchar(11) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
    RideName varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
    VehicleName varchar(11) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
    ProviderEarning decimal(10,2) DEFAULT NULL,
    TotalEarning decimal(10,2) DEFAULT NULL,
    PaymentMode varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'cash',
    CardId varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
    IsActive varchar(11) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'yes',
    ProviderRejectedIds json DEFAULT NULL,
    IsUserReviewed varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'no',
    IsCouponApplied varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'no',
    RedeemedId int(11) DEFAULT NULL,
    DiscountAmount decimal(10,2) DEFAULT NULL,
    CouponCode varchar(50) DEFAULT NULL,
    BookingType varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'now',
    SeatCount int(11) DEFAULT '0',
    EmailStatus varchar(5) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 'no',
    BookingTimestamp timestamp NULL DEFAULT NULL,
    CreateAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdateAt timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (Id)
  ) ENGINE=InnoDB AUTO_INCREMENT=4954 DEFAULT CHARSET=utf8;`,
  'down': 'DROP TABLE Booking'
}
